version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"

  newsaggregator-container:
    build: .
    env_file:
      - .env
    depends_on:
      - sqlserver
    ports:
      - "5001:80"